"""Identity & access (A1..A8) — schema, sessions, OIDC, local password, lockout."""

from backend_app.identity.jwks import (
    HttpxJwksFetcher,
    IdTokenVerificationError,
    IdTokenVerifier,
    JwksFetcherError,
    JwksProvider,
)
from backend_app.identity.lockout import (
    AccountLocked,
    LockoutService,
)
from backend_app.identity.lockout_store import (
    InMemoryLockoutStore,
    LockoutStore,
    PostgresLockoutStore,
)
from backend_app.identity.mfa import (
    MfaChallengeInvalid,
    MfaCodeRejected,
    MfaConfig,
    MfaError,
    MfaFactorDisabled,
    MfaFactorNotFound,
    MfaService,
    MfaWebAuthnRejected,
)
from backend_app.identity.me_store import (
    InMemoryMeStore,
    MeStore,
    PostgresMeStore,
    UserPreferencesRecord,
    UserProfileRecord,
)
from backend_app.identity.mfa_store import (
    InMemoryMfaStore,
    MfaStore,
    PostgresMfaStore,
)
from backend_app.identity.oidc import (
    HttpxTokenEndpointClient,
    OidcConfigError,
    OidcProviderConfig,
    OidcProviderDisabled,
    OidcService,
    OidcStateMismatch,
    OidcTokenExchangeError,
    OidcUserNotProvisioned,
    TokenEndpointClient,
)
from backend_app.identity.oidc_store import (
    InMemoryOidcStore,
    OidcStore,
    PostgresOidcStore,
)
from backend_app.identity.password_store import (
    InMemoryPasswordStore,
    PasswordStore,
    PostgresPasswordStore,
)
from backend_app.identity._saml_lib import (
    BuiltAuthnRequest,
    FakeSamlVerifier,
    OneLoginSamlVerifier,
    ParsedSamlAssertion,
    SamlAssertionExpired,
    SamlAudienceMismatch,
    SamlInResponseToMismatch,
    SamlMissingAssertion,
    SamlProviderConfig,
    SamlSignatureError,
    SamlVerifier,
    SamlVerifierError,
)
from backend_app.identity.saml import (
    SamlConfigError,
    SamlIdpInitiatedDisabled,
    SamlProviderDisabled,
    SamlService,
    SamlUserNotProvisioned,
)
from backend_app.identity.saml_store import (
    InMemorySamlStore,
    PostgresSamlStore,
    SamlAuthenticationNotFound,
    SamlReplayDetected,
    SamlStore,
)
from backend_app.identity.scim import (
    ResolvedScimToken,
    ScimAuthError,
    ScimBadRequest,
    ScimConflict,
    ScimError,
    ScimNotFound,
    ScimService,
    ScimUnsupportedFilter,
)
from backend_app.identity.scim_filter import ScimFilterError
from backend_app.identity.scim_store import (
    InMemoryScimStore,
    PostgresScimStore,
    ScimStore,
)
from backend_app.identity.passwords import (
    BootstrapAdminService,
    BootstrapRefused,
    LocalAuthDisabled,
    LoginRejectedError,
    PasswordChangeRejected,
    PasswordHasherConfig,
    PasswordService,
    ResetTokenRejected,
    WeakPasswordError,
)

# LocalAuthDisabled is consumed by the password routes which import it via
# the identity package. Re-exported above; nothing else to add.
from backend_app.identity.session_store import (
    InMemorySessionStore,
    PostgresSessionStore,
    SessionStore,
)
from backend_app.identity.sessions import (
    DevMintNotAllowed,
    SessionAuthSecretMissing,
    SessionInvalidToken,
    SessionNotActive,
    SessionPolicy,
    SessionService,
    audit_session_event,
)
from backend_app.identity.store import (
    IdentityStore,
    InMemoryIdentityStore,
    PostgresIdentityStore,
)


__all__ = [
    "AccountLocked",
    "BootstrapAdminService",
    "BootstrapRefused",
    "BuiltAuthnRequest",
    "DevMintNotAllowed",
    "FakeSamlVerifier",
    "HttpxJwksFetcher",
    "HttpxTokenEndpointClient",
    "IdTokenVerificationError",
    "IdTokenVerifier",
    "IdentityStore",
    "InMemoryIdentityStore",
    "InMemoryLockoutStore",
    "InMemoryMeStore",
    "InMemoryMfaStore",
    "InMemoryOidcStore",
    "InMemoryPasswordStore",
    "InMemorySamlStore",
    "InMemorySessionStore",
    "JwksFetcherError",
    "JwksProvider",
    "LocalAuthDisabled",
    "LockoutService",
    "LockoutStore",
    "LoginRejectedError",
    "MeStore",
    "MfaChallengeInvalid",
    "MfaCodeRejected",
    "MfaConfig",
    "MfaError",
    "MfaFactorDisabled",
    "MfaFactorNotFound",
    "MfaService",
    "MfaStore",
    "MfaWebAuthnRejected",
    "OidcConfigError",
    "OidcProviderConfig",
    "OidcProviderDisabled",
    "OidcService",
    "OidcStateMismatch",
    "OidcStore",
    "OidcTokenExchangeError",
    "OidcUserNotProvisioned",
    "OneLoginSamlVerifier",
    "ParsedSamlAssertion",
    "PasswordChangeRejected",
    "PasswordHasherConfig",
    "PasswordService",
    "PasswordStore",
    "PostgresIdentityStore",
    "PostgresLockoutStore",
    "PostgresMeStore",
    "PostgresMfaStore",
    "PostgresOidcStore",
    "PostgresPasswordStore",
    "PostgresSamlStore",
    "PostgresSessionStore",
    "ResetTokenRejected",
    "SamlAssertionExpired",
    "SamlAudienceMismatch",
    "SamlAuthenticationNotFound",
    "SamlConfigError",
    "SamlIdpInitiatedDisabled",
    "SamlInResponseToMismatch",
    "SamlMissingAssertion",
    "SamlProviderConfig",
    "SamlProviderDisabled",
    "SamlReplayDetected",
    "SamlService",
    "SamlSignatureError",
    "SamlStore",
    "SamlUserNotProvisioned",
    "SamlVerifier",
    "SamlVerifierError",
    "InMemoryScimStore",
    "PostgresScimStore",
    "ResolvedScimToken",
    "ScimAuthError",
    "ScimBadRequest",
    "ScimConflict",
    "ScimError",
    "ScimFilterError",
    "ScimNotFound",
    "ScimService",
    "ScimStore",
    "ScimUnsupportedFilter",
    "SessionAuthSecretMissing",
    "SessionInvalidToken",
    "SessionNotActive",
    "SessionPolicy",
    "SessionService",
    "SessionStore",
    "TokenEndpointClient",
    "UserPreferencesRecord",
    "UserProfileRecord",
    "WeakPasswordError",
    "audit_session_event",
]
