#!/usr/bin/env bash
#
# 0xCopilot self-host installer.
#
#   curl -fsSL https://raw.githubusercontent.com/0x-copilot-dev/0x-copilot/main/deploy/self-host/install.sh | bash
#
# Idempotent: downloads the compose file, generates strong secrets on the first
# run (and never overwrites them afterwards), pulls the published images, boots
# the stack, and waits for the gateway to report healthy. Re-run any time to
# pull newer images and reconcile.

set -euo pipefail

REPO_RAW="${OXC_REPO_RAW:-https://raw.githubusercontent.com/0x-copilot-dev/0x-copilot/main/deploy/self-host}"
INSTALL_DIR="${OXC_INSTALL_DIR:-${HOME}/0x-copilot}"
COMPOSE_FILE="docker-compose.yml"
ENV_FILE=".env"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---- Preflight --------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker is not installed. See https://docs.docker.com/get-docker/"

if ! docker compose version >/dev/null 2>&1; then
  die "the Docker Compose v2 plugin is required (need >= 2.23.1). 'docker compose version' failed."
fi

if ! docker info >/dev/null 2>&1; then
  die "the Docker daemon is not reachable. Start Docker and re-run."
fi

command -v openssl >/dev/null 2>&1 || die "openssl is required to generate secrets."

# ---- Fetch helper -----------------------------------------------------------
fetch() {
  # fetch <url> <dest>
  url="$1"; dest="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$url" -o "$dest"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO "$dest" "$url"
  else
    die "need curl or wget to download files."
  fi
}

# ---- Layout -----------------------------------------------------------------
log "Installing into ${INSTALL_DIR}"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

log "Downloading compose file"
fetch "${REPO_RAW}/docker-compose.prod.yml" "$COMPOSE_FILE"

if [ ! -f "${ENV_FILE}.example" ]; then
  fetch "${REPO_RAW}/.env.example" "${ENV_FILE}.example"
fi

# ---- Secrets (generate once; never clobber) ---------------------------------
if [ -f "$ENV_FILE" ]; then
  log "Keeping existing ${ENV_FILE} (secrets preserved)"
else
  log "Generating ${ENV_FILE} with fresh secrets"
  auth_secret="$(openssl rand -hex 64)"
  service_token="$(openssl rand -hex 32)"
  vault_secret="$(openssl rand -hex 32)"
  audit_key="$(openssl rand -hex 32)"
  pg_password="$(openssl rand -hex 24)"
  gateway_port="${OXC_GATEWAY_PORT:-8080}"
  siwe_origin="${OXC_SIWE_ORIGIN:-http://localhost:${gateway_port}}"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Keep this file secret.
GHCR_NAMESPACE=ghcr.io/0x-copilot-dev
IMAGE_TAG=latest

GATEWAY_PORT=${gateway_port}

ENTERPRISE_AUTH_SECRET=${auth_secret}
ENTERPRISE_SERVICE_TOKEN=${service_token}
MCP_TOKEN_VAULT_SECRET=${vault_secret}
AUDIT_HMAC_KEY=${audit_key}

POSTGRES_USER=atlas
POSTGRES_PASSWORD=${pg_password}

SIWE_ORIGIN=${siwe_origin}
SIWE_ALLOWED_CHAIN_IDS=1,8453,42161,4663

GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=

OPENAI_API_KEY=
ANTHROPIC_API_KEY=
GOOGLE_API_KEY=

AI_BACKEND_WORKERS=2
EOF
  umask 022
fi

# ---- Pull + boot ------------------------------------------------------------
log "Pulling images"
if ! docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull; then
  warn "Image pull failed. If the GHCR packages are private, authenticate first:"
  warn "  echo <GITHUB_PAT_with_read:packages> | docker login ghcr.io -u <github-username> --password-stdin"
  warn "Then re-run this installer."
  die "cannot continue without images."
fi

log "Starting the stack"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d

# ---- Wait for health --------------------------------------------------------
gateway_port="$(grep -E '^GATEWAY_PORT=' "$ENV_FILE" | head -n1 | cut -d= -f2)"
gateway_port="${gateway_port:-8080}"
url="http://localhost:${gateway_port}/v1/health"

log "Waiting for the gateway at ${url}"
ready=""
i=0
while [ "$i" -lt 60 ]; do
  if command -v curl >/dev/null 2>&1; then
    if curl -fsS "$url" >/dev/null 2>&1; then ready=1; break; fi
  elif command -v wget >/dev/null 2>&1; then
    if wget -qO- "$url" >/dev/null 2>&1; then ready=1; break; fi
  fi
  i=$((i + 1))
  sleep 2
done

echo
if [ -n "$ready" ]; then
  log "0xCopilot is up."
else
  warn "Gateway did not report healthy within ~2 minutes."
  warn "Check logs:  (cd ${INSTALL_DIR} && docker compose logs -f)"
fi

cat <<EOF

  Open           http://localhost:${gateway_port}/
  Sign in        connect a wallet, or set GOOGLE_OAUTH_CLIENT_ID/SECRET in
                 ${INSTALL_DIR}/${ENV_FILE} and re-run to enable "Continue with Google"
  Add a key      Settings -> Providers (BYOK) — paste your OpenAI/Anthropic/Google key
  Public URL     set SIWE_ORIGIN in ${ENV_FILE} to your real origin, then:
                   (cd ${INSTALL_DIR} && docker compose up -d)
  Manage         cd ${INSTALL_DIR}
                   docker compose ps
                   docker compose logs -f
                   docker compose down          # stop
                   docker compose down -v        # stop + delete all data

EOF
