"""Desktop capability adapters — ai-backend side of the Electron capability broker.

AC5 slice 3a: a read-only Deep Agents backend (``/workspace/``) over user-granted
host folders, driven by a thin async client to the loopback capability broker.
"""

from __future__ import annotations

from agent_runtime.capabilities.desktop.broker_client import (
    BrokerClientConfig,
    BrokerError,
    BrokerGrant,
    BrokerGrantRequiredError,
    BrokerGrantSnapshot,
    BrokerInvalidPathError,
    BrokerInvalidRequestError,
    BrokerNotADirectoryError,
    BrokerNotAFileError,
    BrokerNotFoundError,
    BrokerPermissionDeniedError,
    BrokerProtocolError,
    BrokerTooLargeError,
    BrokerUnavailableError,
    BrokerUnsupportedError,
    DesktopBrokerClient,
    WorkspaceAuthorityDeniedError,
    WorkspaceCommitResult,
    WorkspaceConflictError,
    WorkspaceHostSession,
    WorkspaceHostSessionGrant,
    WorkspacePreconditionDriftError,
    WorkspacePreparedEffect,
    WorkspaceUploadSlot,
)
from agent_runtime.capabilities.desktop.workspace_authority import (
    BrokerWorkspaceAuthority,
    ImmutableWorkspaceContentResolver,
    WorkspaceAuthorityContractError,
    WorkspaceAuthorityPort,
    WorkspaceChangeEntry,
    WorkspaceEffectExecutor,
    WorkspacePrecondition,
    WorkspacePrepareCommand,
    WorkspaceProposalMaterial,
    WorkspaceProposalResolver,
)
from agent_runtime.capabilities.desktop.workspace_backend import (
    ROUTE_PREFIX,
    BrokeredWorkspaceBackend,
    WorkspaceBackendConfig,
    WorkspaceMount,
    WorkspaceMountTable,
    WorkspaceMutationSnapshot,
    WorkspaceSnapshotEmitter,
    WorkspaceSnapshotError,
    WorkspaceSnapshotStore,
    WorkspaceWriteNotSupportedError,
    build_workspace_backend,
)

__all__ = [
    "ROUTE_PREFIX",
    "BrokerClientConfig",
    "BrokerError",
    "BrokerGrant",
    "BrokerGrantRequiredError",
    "BrokerGrantSnapshot",
    "BrokerInvalidPathError",
    "BrokerInvalidRequestError",
    "BrokerNotADirectoryError",
    "BrokerNotAFileError",
    "BrokerNotFoundError",
    "BrokerPermissionDeniedError",
    "BrokerProtocolError",
    "BrokerTooLargeError",
    "BrokerUnavailableError",
    "BrokerUnsupportedError",
    "BrokerWorkspaceAuthority",
    "BrokeredWorkspaceBackend",
    "DesktopBrokerClient",
    "ImmutableWorkspaceContentResolver",
    "WorkspaceBackendConfig",
    "WorkspaceAuthorityContractError",
    "WorkspaceAuthorityDeniedError",
    "WorkspaceAuthorityPort",
    "WorkspaceChangeEntry",
    "WorkspaceCommitResult",
    "WorkspaceConflictError",
    "WorkspaceHostSession",
    "WorkspaceHostSessionGrant",
    "WorkspaceEffectExecutor",
    "WorkspaceMount",
    "WorkspaceMountTable",
    "WorkspacePrecondition",
    "WorkspacePreconditionDriftError",
    "WorkspacePrepareCommand",
    "WorkspacePreparedEffect",
    "WorkspaceProposalMaterial",
    "WorkspaceProposalResolver",
    "WorkspaceMutationSnapshot",
    "WorkspaceSnapshotEmitter",
    "WorkspaceSnapshotError",
    "WorkspaceSnapshotStore",
    "WorkspaceWriteNotSupportedError",
    "WorkspaceUploadSlot",
    "build_workspace_backend",
]
