-- PR 4.3: workspace-level behavior overrides.
--
-- Adds one JSONB column to ``workspace_defaults`` (PR 1.6 / migration
-- 0019) holding the small, opinion-shaped policy knobs that every new
-- chat / run inherits when the request omits them:
--
--   {
--     "system_prompt_override":    "string up to 8 KB" | null,
--     "temperature":                0.0..1.0           | null,
--     "citation_density":           "minimal" | "standard" | "thorough" | null,
--     "refusal_behavior":           "standard" | "strict" | "permissive" | null,
--     "default_reasoning_effort":   "low" | "medium" | "high" | null,
--     "training_data_opt_out":      bool (default false)
--   }
--
-- Storage shape rationale (see docs/new-design/pr-4.3-...md §2.2):
--   * Single JSONB blob — five knobs, all opinion-shaped, evolve together.
--     Five typed columns would mean five future migrations as the design
--     evolves; one blob means none. Pydantic v2 strict-mode validates the
--     keys at write so unknown keys are rejected; we never query by
--     substructure (the runtime resolver only reads the keys it knows).
--   * NOT NULL DEFAULT '{}'::jsonb — metadata-only on Postgres 14+; no
--     row rewrite. Old rows materialise to the deployment defaults via
--     the existing fallback chain in ``ModelConfigResolver`` /
--     ``WorkspaceDefaultsService``.
--
-- RLS unchanged: the table-level ``tenant_isolation`` policy from
-- migration 0019 covers this column too.

ALTER TABLE workspace_defaults
    ADD COLUMN IF NOT EXISTS behavior_overrides JSONB NOT NULL DEFAULT '{}'::jsonb;
