"""Conservative capability-concurrency domain for F6.

The whole domain shares one vocabulary in
:mod:`agent_runtime.capabilities.concurrency.contracts` and one error family in
:mod:`agent_runtime.capabilities.concurrency.errors`. Everything else is a
policy over those types: descriptor precedence, batch planning, scoped permits,
and serial kill switches.

:mod:`agent_runtime.capabilities.concurrency.batch_journal_store` is
deliberately **not** re-exported here. It is the one F6 module that knows the
run-event transport schema, and that schema imports this package's record
vocabulary — so importing the adapter from this ``__init__`` would close a
cycle. Import it by module path.
"""

from agent_runtime.capabilities.concurrency.batch_coordinator import (
    BatchAdmissionOutcome,
    BatchAllowanceSupplier,
    BatchChildAdmission,
    BatchChildIdentity,
    BatchChildOutcome,
    BatchChildResult,
    BatchChildRunner,
    BatchChildStatus,
    BatchClock,
    BatchCoordinatorBounds,
    BatchCoordinatorError,
    BatchCoordinatorMessages,
    BatchExecutionCoordinator,
    BatchExecutionReport,
    BatchExecutionStatus,
    BatchPermitScopeFactory,
)
from agent_runtime.capabilities.concurrency.batch_journal import (
    BATCH_JOURNAL_RECORD_ADAPTER,
    BatchJournalConflict,
    BatchJournalCorruption,
    BatchJournalError,
    BatchJournalLimits,
    BatchJournalPatterns,
    BatchJournalRecord,
    BatchJournalRecordKind,
    BatchJournalScopeConflict,
    BatchJournalSnapshotConflict,
    BatchJournalWrite,
    BatchPlanBoundRecord,
    BatchPlanRecorder,
    BatchPlanRequest,
    BatchPlanStorePort,
    BatchRecoveryView,
    DurableBatchPlan,
    PlannedOperation,
    SequencedBatchJournalRecord,
    validate_batch_journal_record,
)
from agent_runtime.capabilities.concurrency.child_execution import (
    BatchChildDispatch,
    BatchChildDispatchPort,
    BatchChildDispatchStatus,
    BatchChildExecutionBounds,
    BatchChildExecutionError,
    BatchChildExecutionMessages,
    BatchChildExecutionReason,
    BatchChildExecutorMisconfigured,
    BatchChildWork,
    BatchChildWorkPort,
    GatewayBatchChildExecutor,
    RunScopedBatchChildWork,
)
from agent_runtime.capabilities.concurrency.contracts import (
    BatchFailurePolicy,
    BatchOperation,
    BatchPlan,
    BatchSegment,
    BatchSegmentMode,
    BatchSegmentReason,
    ConcurrencyAllowance,
    ConcurrencyBounds,
    ConcurrencyMode,
    ConcurrencyPolicy,
    ConcurrencyPolicyField,
    ConcurrencyScope,
    IdempotencyKind,
    NarrowableEnum,
    OperationBatch,
    OrderingRequirement,
    PermitAcquisitionRequest,
    PermitBounds,
    PermitCapacity,
    PermitCapacityPolicy,
    PermitLease,
    PermitOutcome,
    PermitScope,
    PermitScopeKey,
    PermitWaitMode,
    PolicySource,
    ProviderSessionConstraint,
    ResourceKeyDimension,
    ResourceKeyTemplate,
    SideEffectKind,
)
from agent_runtime.capabilities.concurrency.descriptor_policy import (
    CapabilityConcurrencyDeclaration,
    ConcurrencyDescriptorParser,
    ConcurrencyNarrowing,
    ConcurrencyPolicyRejection,
    ConcurrencyPolicyResolution,
    ConcurrencyPolicyResolver,
)
from agent_runtime.capabilities.concurrency.errors import (
    ConcurrencyDeclarationRejected,
    ConcurrencyPolicyError,
    ConcurrencyPolicyWideningRejected,
    ConcurrencyRejectionReason,
    PermitDoubleReleaseError,
    PermitError,
    PermitErrorCode,
    PermitEventLoopMismatchError,
    PermitNotAdmittedError,
    ResourceKeyRenderRejected,
    ResourceKeyTemplateRejected,
)
from agent_runtime.capabilities.concurrency.kill_switches import (
    ConcurrencyKillSwitchDecision,
    ConcurrencyKillSwitchDirectives,
    ConcurrencyKillSwitchError,
    ConcurrencyKillSwitchGate,
    ConcurrencyKillSwitchReason,
    ConcurrencyKillSwitchResolver,
    ConcurrencyKillSwitchScope,
    ConcurrencyKillSwitchSourcePort,
    ConcurrencyKillSwitchSourceStatus,
    ConcurrencyKillSwitchTarget,
    ConcurrencyKillSwitchTargetError,
)
from agent_runtime.capabilities.concurrency.permits import RunPermitManager
from agent_runtime.capabilities.concurrency.planner import BatchPlanner

__all__ = (
    "BATCH_JOURNAL_RECORD_ADAPTER",
    "BatchAdmissionOutcome",
    "BatchAllowanceSupplier",
    "BatchChildAdmission",
    "BatchChildDispatch",
    "BatchChildDispatchPort",
    "BatchChildDispatchStatus",
    "BatchChildExecutionBounds",
    "BatchChildExecutionError",
    "BatchChildExecutionMessages",
    "BatchChildExecutionReason",
    "BatchChildExecutorMisconfigured",
    "BatchChildIdentity",
    "BatchChildOutcome",
    "BatchChildResult",
    "BatchChildRunner",
    "BatchChildStatus",
    "BatchChildWork",
    "BatchChildWorkPort",
    "BatchClock",
    "BatchCoordinatorBounds",
    "BatchCoordinatorError",
    "BatchCoordinatorMessages",
    "BatchExecutionCoordinator",
    "BatchExecutionReport",
    "BatchExecutionStatus",
    "BatchFailurePolicy",
    "BatchJournalConflict",
    "BatchJournalCorruption",
    "BatchJournalError",
    "BatchJournalLimits",
    "BatchJournalPatterns",
    "BatchJournalRecord",
    "BatchJournalRecordKind",
    "BatchJournalScopeConflict",
    "BatchJournalSnapshotConflict",
    "BatchJournalWrite",
    "BatchOperation",
    "BatchPlan",
    "BatchPlanBoundRecord",
    "BatchPlanRecorder",
    "BatchPlanRequest",
    "BatchPermitScopeFactory",
    "BatchPlanStorePort",
    "BatchPlanner",
    "BatchRecoveryView",
    "BatchSegment",
    "BatchSegmentMode",
    "BatchSegmentReason",
    "CapabilityConcurrencyDeclaration",
    "ConcurrencyAllowance",
    "ConcurrencyBounds",
    "ConcurrencyDeclarationRejected",
    "ConcurrencyDescriptorParser",
    "ConcurrencyKillSwitchDecision",
    "ConcurrencyKillSwitchDirectives",
    "ConcurrencyKillSwitchError",
    "ConcurrencyKillSwitchGate",
    "ConcurrencyKillSwitchReason",
    "ConcurrencyKillSwitchResolver",
    "ConcurrencyKillSwitchScope",
    "ConcurrencyKillSwitchSourcePort",
    "ConcurrencyKillSwitchSourceStatus",
    "ConcurrencyKillSwitchTarget",
    "ConcurrencyKillSwitchTargetError",
    "ConcurrencyMode",
    "ConcurrencyNarrowing",
    "ConcurrencyPolicy",
    "ConcurrencyPolicyError",
    "ConcurrencyPolicyField",
    "ConcurrencyPolicyRejection",
    "ConcurrencyPolicyResolution",
    "ConcurrencyPolicyResolver",
    "ConcurrencyPolicyWideningRejected",
    "ConcurrencyRejectionReason",
    "ConcurrencyScope",
    "DurableBatchPlan",
    "GatewayBatchChildExecutor",
    "IdempotencyKind",
    "NarrowableEnum",
    "OperationBatch",
    "OrderingRequirement",
    "PermitAcquisitionRequest",
    "PermitBounds",
    "PermitCapacity",
    "PermitCapacityPolicy",
    "PermitDoubleReleaseError",
    "PermitError",
    "PermitErrorCode",
    "PermitEventLoopMismatchError",
    "PermitLease",
    "PermitNotAdmittedError",
    "PermitOutcome",
    "PermitScope",
    "PermitScopeKey",
    "PermitWaitMode",
    "PlannedOperation",
    "PolicySource",
    "ProviderSessionConstraint",
    "ResourceKeyDimension",
    "ResourceKeyRenderRejected",
    "ResourceKeyTemplate",
    "ResourceKeyTemplateRejected",
    "RunPermitManager",
    "RunScopedBatchChildWork",
    "SequencedBatchJournalRecord",
    "SideEffectKind",
    "validate_batch_journal_record",
)
