"""Subagent catalog, handoff, authority, and delegation-planning primitives."""

from agent_runtime.delegation.subagents.contracts import (
    AsyncSubagentLaunch,
    AsyncTaskLifecycleResult,
    AsyncTaskState,
    AsyncTaskStatus,
    RuntimeContextReference,
    SubagentArtifact,
    SubagentDefinition,
    SubagentError,
    SubagentErrorCode,
    SubagentOutputContract,
    SubagentResult,
    SubagentTask,
    SubagentTransport,
)
from agent_runtime.delegation.subagents.coordination import (
    DelegationAdmissionCode,
    DelegationAdmissionError,
    DelegationAdmissionPolicy,
    DelegationBudget,
    DelegationContextPacket,
    DelegationCoordinator,
    DelegationDispatchMode,
    DelegationParentState,
    DelegationPlan,
    DelegationPlanEntry,
    DelegationRequest,
)
from agent_runtime.delegation.subagents.authority import (
    SubagentAuthorityError,
    SubagentAuthorityPolicy,
    SubagentCapabilityGrant,
    SubagentPolicyGrant,
)
from agent_runtime.delegation.subagents.operation_identity import (
    SUBAGENT_DELEGATION_OPERATION_ID_KEY,
    SUBAGENT_PARENT_OPERATION_ID_KEY,
    SUBAGENT_ROOT_OPERATION_ID_KEY,
    SUPERVISOR_TASK_CALL_ID_KEY,
    SubagentOperationIdentityFactory,
    SubagentOperationLink,
)
from agent_runtime.delegation.subagents.definitions import (
    DynamicSubagentCatalog,
    RegisteredSubagent,
    SubagentDefinitionProvider,
    SubagentPermissionPolicy,
)
from agent_runtime.delegation.subagents.handoff import (
    SubagentHandoffBuilder,
    SubagentHandoffPolicy,
)

__all__ = [
    "AsyncSubagentLaunch",
    "AsyncTaskLifecycleResult",
    "AsyncTaskState",
    "AsyncTaskStatus",
    "DelegationAdmissionCode",
    "DelegationAdmissionError",
    "DelegationAdmissionPolicy",
    "DelegationBudget",
    "DelegationContextPacket",
    "DelegationCoordinator",
    "DelegationDispatchMode",
    "DelegationParentState",
    "DelegationPlan",
    "DelegationPlanEntry",
    "DelegationRequest",
    "DynamicSubagentCatalog",
    "RegisteredSubagent",
    "RuntimeContextReference",
    "SUBAGENT_DELEGATION_OPERATION_ID_KEY",
    "SUBAGENT_PARENT_OPERATION_ID_KEY",
    "SUBAGENT_ROOT_OPERATION_ID_KEY",
    "SUPERVISOR_TASK_CALL_ID_KEY",
    "SubagentArtifact",
    "SubagentAuthorityError",
    "SubagentAuthorityPolicy",
    "SubagentCapabilityGrant",
    "SubagentDefinition",
    "SubagentDefinitionProvider",
    "SubagentError",
    "SubagentErrorCode",
    "SubagentHandoffBuilder",
    "SubagentHandoffPolicy",
    "SubagentOperationIdentityFactory",
    "SubagentOperationLink",
    "SubagentOutputContract",
    "SubagentPermissionPolicy",
    "SubagentResult",
    "SubagentTask",
    "SubagentTransport",
    "SubagentPolicyGrant",
]
