import type { AuthSession } from "./oidc-client";
import { fetchProfileClaims } from "./profile-claims";

// "Use locally, no account" — the device account (backend PR #166).
//
// One POST to the facade mints a REAL session for the deployment's single
// device account (`local_accounts` singleton edge; find-or-create is
// DB-arbitrated, so every "Use locally" — across restarts, reinstalls and
// races — resolves to the SAME account, D4-A):
//
//   1. POST {facade}/v1/auth/local/session   (x-enterprise-service-token)
//   2. best-effort GET /v1/me/profile to fill renderer-facing display claims
//
// The header is the per-install HOST secret generated by the supervisor and
// held only by this main process — the reason a browser page can never mint
// this session (localhost is reachable by any open tab; the token is not).
// The bearer never leaves the main process; the caller persists it like every
// other sign-in mode.
//
// History: this flow previously minted a synthetic per-install Ethereum key
// and drove the SIWE ramp in-process. That produced a *wallet* account that
// lied about its nature (profile showed a wallet the user never owned) and
// forked a fresh account whenever the keychain entry was lost. The device
// account replaces it: honest `auth_method: "local"`, server-side singleton.

const DEFAULT_SESSION_TTL_MS = 60 * 60 * 1000;
const HOST_TOKEN_HEADER = "x-enterprise-service-token";

export interface LocalLoginDeps {
  readonly facadeBaseUrl: string;
  /**
   * The per-install host secret (ENTERPRISE_SERVICE_TOKEN) from the boot
   * secrets — proves the caller is the app's own main process.
   */
  readonly hostToken: string;
  readonly fetch?: typeof fetch;
  readonly clock?: () => number;
}

export class LocalLoginError extends Error {
  readonly stage: "mint";

  constructor(message: string) {
    super(message);
    this.name = "LocalLoginError";
    this.stage = "mint";
  }
}

interface LocalSessionHandoff {
  readonly user_id: string;
  readonly org_id: string;
  readonly session_id: string;
  readonly bearer_token: string;
  readonly expires_at: string;
  readonly created: boolean;
}

function trimTrailingSlash(url: string): string {
  return url.endsWith("/") ? url.slice(0, -1) : url;
}

async function safeText(response: Response): Promise<string> {
  try {
    return await response.text();
  } catch {
    return "";
  }
}

export async function runLocalLogin(
  workspaceId: string,
  deps: LocalLoginDeps,
): Promise<AuthSession> {
  const facadeBaseUrl = trimTrailingSlash(deps.facadeBaseUrl);
  const doFetch = deps.fetch ?? globalThis.fetch.bind(globalThis);
  const clock = deps.clock ?? Date.now;

  if (deps.hostToken === "") {
    // Fail closed with an actionable message rather than a bare 401: the
    // token is generated by the supervisor, so its absence means the app is
    // running without a supervised backend (e.g. plain dev shell).
    throw new LocalLoginError(
      "local sign-in requires the supervised backend (host token unavailable)",
    );
  }

  const response = await doFetch(`${facadeBaseUrl}/v1/auth/local/session`, {
    method: "POST",
    headers: { [HOST_TOKEN_HEADER]: deps.hostToken },
  });
  if (!response.ok) {
    throw new LocalLoginError(
      `local sign-in failed: ${response.status} ${await safeText(response)}`,
    );
  }
  const handoff = (await response.json()) as LocalSessionHandoff;

  // Best-effort display claims (same helper every other flow uses).
  const claims = await fetchProfileClaims(
    doFetch,
    facadeBaseUrl,
    handoff.bearer_token,
    handoff.user_id,
    workspaceId,
  );

  const expiresAtMs = Date.parse(handoff.expires_at);
  return {
    idToken: null,
    accessToken: handoff.bearer_token,
    refreshToken: null,
    expiresAt: Number.isNaN(expiresAtMs)
      ? clock() + DEFAULT_SESSION_TTL_MS
      : expiresAtMs,
    claims,
  };
}
