"""Policy-aware compact capability discovery."""

from agent_runtime.capabilities.discovery.activation import (
    CapabilityActivationDecision,
    CapabilityActivationError,
    CapabilityActivationMode,
    CapabilityActivationReason,
    CapabilityActivationResolver,
)
from agent_runtime.capabilities.discovery.builder import AuthorizedCatalogBuilder
from agent_runtime.capabilities.discovery.contracts import (
    ApprovalCue,
    CapabilityCandidate,
    CapabilityCatalog,
    CapabilityCatalogGeneration,
    CapabilityCatalogIdentityError,
    CapabilityDescribeRequest,
    CapabilityDescribeResult,
    CapabilityDescribeToolResult,
    CapabilityDescription,
    CapabilityDiscoveryError,
    CapabilityDiscoveryErrorCode,
    CapabilityCatalogRevision,
    CapabilityCatalogScope,
    CapabilityIndexEntry,
    CapabilityParameterHint,
    CapabilityRefBinding,
    CapabilitySearchFilters,
    CapabilitySearchRequest,
    CapabilitySearchResult,
    CapabilitySearchToolResult,
    CapabilitySource,
    CatalogDescriptorRevision,
    CatalogEffectClass,
)
from agent_runtime.capabilities.discovery.ranker import DeterministicLexicalRanker
from agent_runtime.capabilities.discovery.tool_bridge import (
    CapabilityCatalogAccess,
    CapabilityDescribeTool,
    CapabilitySearchTool,
)

__all__ = [
    "ApprovalCue",
    "AuthorizedCatalogBuilder",
    "CapabilityActivationDecision",
    "CapabilityActivationError",
    "CapabilityActivationMode",
    "CapabilityActivationReason",
    "CapabilityActivationResolver",
    "CapabilityCandidate",
    "CapabilityCatalog",
    "CapabilityCatalogAccess",
    "CapabilityCatalogGeneration",
    "CapabilityCatalogIdentityError",
    "CapabilityCatalogRevision",
    "CapabilityCatalogScope",
    "CapabilityDescribeRequest",
    "CapabilityDescribeResult",
    "CapabilityDescribeTool",
    "CapabilityDescribeToolResult",
    "CapabilityDescription",
    "CapabilityDiscoveryError",
    "CapabilityDiscoveryErrorCode",
    "CapabilityIndexEntry",
    "CapabilityParameterHint",
    "CapabilityRefBinding",
    "CapabilitySearchFilters",
    "CapabilitySearchRequest",
    "CapabilitySearchResult",
    "CapabilitySearchTool",
    "CapabilitySearchToolResult",
    "CapabilitySource",
    "CatalogDescriptorRevision",
    "CatalogEffectClass",
    "DeterministicLexicalRanker",
]
