"""Durable persistence records grouped by aggregate."""

from agent_runtime.persistence.records.approval_batches import (
    ApprovalBatchItemRecord,
    ApprovalBatchRecord,
    ApprovalBatchSpec,
    ApprovalBatchStatus,
    BatchItemDecision,
    BatchOutcomeStatus,
    BatchTransitionOutcome,
)
from agent_runtime.persistence.records.budgets import (
    BudgetEnforcement,
    BudgetPeriod,
    BudgetRecord,
    BudgetReservationRecord,
    BudgetScope,
    BudgetStateRecord,
    BudgetStatus,
    BudgetWithState,
    ChargeOutcome,
)
from agent_runtime.persistence.records.citations import CitationRecord
from agent_runtime.persistence.records.drafts import (
    DraftEffectSupersession,
    DraftPath,
    DraftRecord,
    DraftStatus,
)
from agent_runtime.persistence.records.common import (
    ApprovalRiskClass,
    AsyncTaskStatus,
    AuditActorType,
    AuditOutcome,
    OutboxStatus,
    PersistenceApprovalStatus,
    PersistenceValueNormalizer,
    ToolInvocationStatus,
    ToolSideEffectClass,
)
from agent_runtime.persistence.records.outbox import (
    ConsumerCursorRecord,
    OutboxEventRecord,
    RuntimeWorkerClaim,
    RuntimeWorkerResult,
)
from agent_runtime.persistence.records.retention import (
    RetentionDeletionEvidenceRecord,
    RetentionKind,
    RetentionPolicyRecord,
    RetentionScope,
    RetentionSweepOutcome,
)
from agent_runtime.persistence.records.legal_holds import (
    LegalHoldConflict,
    LegalHoldMutationResult,
    LegalHoldReasonCode,
    LegalHoldRecord,
    LegalHoldScope,
)
from agent_runtime.persistence.records.shares import (
    ShareRecipientRecord,
    ShareRecord,
    ShareViewAccess,
)
from agent_runtime.persistence.records.telemetry import (
    CapabilitySnapshotRecord,
    CompressionEventRecord,
    ModelPricingRecord,
    RuntimeContextGraphScope,
    RuntimeContextOccupancyRecord,
    RuntimeModelCallUsageRecord,
    RuntimeRunUsageRecord,
    UsageAttributionEdge,
    UsageAttributionRelationship,
    UsageConversationAggregateRecord,
    UsageDailyConnectorRow,
    UsageDailyOrgRow,
    UsageDailyPurposeRow,
    UsageDailySubagentRow,
    UsageDailyUserRow,
)
from agent_runtime.persistence.records.todo_extractions import (
    TodoExtractionRecord,
    TodoExtractionState,
)
from agent_runtime.persistence.records.tool_budgets import (
    DefaultToolBudget,
    ToolBudgetEnforcement,
    ToolBudgetRecord,
)
from agent_runtime.persistence.records.tool_ordinals import ToolOrdinalBindingRecord
from agent_runtime.persistence.records.tools import ToolInvocationRecord
from agent_runtime.persistence.records.workspace_feeds import (
    SourceAggregate,
    SubagentLifecycleStatus,
    SubagentSnapshot,
    SubagentTokenUsage,
)

PERSISTENCE_TABLE_RECORDS = (
    OutboxEventRecord,
    ConsumerCursorRecord,
    ToolInvocationRecord,
    CompressionEventRecord,
    CapabilitySnapshotRecord,
    CitationRecord,
    DraftRecord,
    ToolOrdinalBindingRecord,
)

__all__ = [
    "OutboxStatus",
    "AsyncTaskStatus",
    "ToolInvocationStatus",
    "ToolSideEffectClass",
    "ApprovalRiskClass",
    "PersistenceApprovalStatus",
    "AuditActorType",
    "AuditOutcome",
    "PersistenceValueNormalizer",
    "OutboxEventRecord",
    "RuntimeWorkerClaim",
    "RuntimeWorkerResult",
    "ConsumerCursorRecord",
    "ToolInvocationRecord",
    "ApprovalBatchItemRecord",
    "ApprovalBatchRecord",
    "ApprovalBatchSpec",
    "ApprovalBatchStatus",
    "BatchItemDecision",
    "BatchOutcomeStatus",
    "BatchTransitionOutcome",
    "CompressionEventRecord",
    "CapabilitySnapshotRecord",
    "ModelPricingRecord",
    "RuntimeContextGraphScope",
    "RuntimeContextOccupancyRecord",
    "RuntimeModelCallUsageRecord",
    "RuntimeRunUsageRecord",
    "UsageAttributionEdge",
    "UsageAttributionRelationship",
    "UsageConversationAggregateRecord",
    "UsageDailyConnectorRow",
    "UsageDailyOrgRow",
    "UsageDailyPurposeRow",
    "UsageDailySubagentRow",
    "UsageDailyUserRow",
    "CitationRecord",
    "DraftPath",
    "DraftEffectSupersession",
    "DraftRecord",
    "DraftStatus",
    "BudgetEnforcement",
    "BudgetPeriod",
    "BudgetRecord",
    "BudgetReservationRecord",
    "BudgetScope",
    "BudgetStateRecord",
    "BudgetStatus",
    "BudgetWithState",
    "ChargeOutcome",
    "TodoExtractionRecord",
    "TodoExtractionState",
    "DefaultToolBudget",
    "ToolBudgetEnforcement",
    "ToolBudgetRecord",
    "ToolOrdinalBindingRecord",
    "RetentionDeletionEvidenceRecord",
    "RetentionKind",
    "RetentionPolicyRecord",
    "RetentionScope",
    "RetentionSweepOutcome",
    "LegalHoldMutationResult",
    "LegalHoldConflict",
    "LegalHoldReasonCode",
    "LegalHoldRecord",
    "LegalHoldScope",
    "ShareRecipientRecord",
    "ShareRecord",
    "ShareViewAccess",
    "SourceAggregate",
    "SubagentLifecycleStatus",
    "SubagentSnapshot",
    "SubagentTokenUsage",
    "PERSISTENCE_TABLE_RECORDS",
]
