"""The "Use locally, no account" session mint (device account).

SECURITY MODEL — this is deliberately NOT a public ramp:

* localhost is reachable by any open browser tab (CSRF-shaped POSTs; DNS
  rebinding can even make responses readable), and this endpoint has no
  inherent proof the way SIWE signatures / OIDC id_tokens are proof. So the
  caller must present the per-install host secret
  (``x-enterprise-service-token``) — generated by the desktop supervisor,
  held by the Electron MAIN process only, never by the renderer or any web
  origin. Browsers cannot supply it (unknown value + CORS preflight).
* Fail-closed, unconditionally: no configured token → 503; wrong or missing
  header → 401. There is no dev fallback on this route.
* Registration is additionally gated on the single-user-desktop deployment
  profile (see ``create_app``): multi-tenant web deployments never expose it.

This is not the dev bypass returning: the mint is an explicit user choice,
provisions a REAL account (org + user + principal + ``local_accounts``
edge), displays honestly as "Local account", and signs the same verified
bearer every other login path gets.
"""

from __future__ import annotations

import os
import secrets

from fastapi import Depends, FastAPI, HTTPException, Request, status

from backend_app.contracts import LocalSessionResult
from backend_app.identity.local_accounts import (
    LocalAccountDisabled,
    LocalAccountService,
)
from backend_app.identity.rbac import public_route
from copilot_service_contracts.headers import SERVICE_TOKEN_HEADER


def _require_host_token(request: Request) -> None:
    expected = os.environ.get("ENTERPRISE_SERVICE_TOKEN", "").strip()
    if not expected:
        raise HTTPException(
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "ENTERPRISE_SERVICE_TOKEN is not configured",
        )
    supplied = request.headers.get(SERVICE_TOKEN_HEADER, "")
    if not secrets.compare_digest(supplied, expected):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "invalid_host_token")


def register_local_auth_routes(app: FastAPI, *, service: LocalAccountService) -> None:
    @app.post(
        "/v1/auth/local/session",
        response_model=LocalSessionResult,
        # Host-token-gated session mint; the RBAC annotation marks it as a
        # session-establishing ramp (like siwe verify) — the REAL gate is
        # _require_host_token, enforced first, fail-closed.
        dependencies=[Depends(public_route())],
    )
    def local_session(request: Request) -> LocalSessionResult:
        _require_host_token(request)
        try:
            mint, user, created = service.ensure_device_session()
        except LocalAccountDisabled as exc:
            raise HTTPException(status.HTTP_403_FORBIDDEN, exc.detail) from exc
        return LocalSessionResult(
            user_id=user.user_id,
            org_id=user.org_id,
            session_id=mint.session_id,
            bearer_token=mint.bearer_token,
            expires_at=mint.expires_at,
            created=created,
        )


__all__ = ["register_local_auth_routes"]
