"""Internal HTTP header names shared by trusted service callers."""

AUTH_HEADER = "authorization"
SERVICE_TOKEN_HEADER = "x-enterprise-service-token"
ORG_HEADER = "x-enterprise-org-id"
USER_HEADER = "x-enterprise-user-id"
ROLES_HEADER = "x-enterprise-roles"
PERMISSION_SCOPES_HEADER = "x-enterprise-permission-scopes"
CONNECTOR_SCOPES_HEADER = "x-enterprise-connector-scopes"
REQUEST_ID_HEADER = "x-request-id"
TRACEPARENT_HEADER = "traceparent"
TRACESTATE_HEADER = "tracestate"
