"""CI guard: assert each service's MANIFEST.lock matches its migrations dir.

Catches:
  - migration files added without updating MANIFEST.lock,
  - migration files modified after they were applied to production
    (checksum drift on a known id),
  - rollback files added/removed without manifest update.

Usage:
    python tools/check_migration_manifest.py            # check all services
    python tools/check_migration_manifest.py --write    # regenerate manifests

Exit code: 0 on success, 1 on drift, 2 on usage error.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


SERVICE_MIGRATION_DIRS: tuple[Path, ...] = (
    REPO_ROOT / "services" / "backend" / "migrations",
    REPO_ROOT / "services" / "ai-backend" / "migrations",
)


def _digest_pair(up_path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(up_path.read_bytes())
    rollback_path = up_path.with_name(f"{up_path.stem}.rollback.sql")
    if rollback_path.exists():
        digest.update(b"\x00")
        digest.update(rollback_path.read_bytes())
    return digest.hexdigest()


def _actual_manifest(migrations_dir: Path) -> dict[str, str]:
    return {
        path.stem: _digest_pair(path)
        for path in sorted(migrations_dir.glob("*.sql"))
        if not path.name.endswith(".rollback.sql")
    }


def _parse_manifest(text: str, *, manifest_path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        try:
            migration_id, marker = line.split(" sha256=", maxsplit=1)
        except ValueError as exc:
            raise SystemExit(
                f"Malformed manifest line in {manifest_path}: {raw!r}"
            ) from exc
        result[migration_id.strip()] = marker.strip()
    return result


def _render_manifest(entries: dict[str, str]) -> str:
    header = (
        "# Auto-generated by tools/check_migration_manifest.py.\n"
        "# Do not hand-edit; CI will refuse if checksums drift from the\n"
        "# migrations/ directory.\n"
    )
    body = "\n".join(
        f"{migration_id} sha256={digest}" for migration_id, digest in entries.items()
    )
    return header + body + "\n"


def _format_diff(actual: dict[str, str], expected: dict[str, str]) -> str:
    lines: list[str] = []
    actual_ids = set(actual)
    expected_ids = set(expected)
    for migration_id in sorted(expected_ids - actual_ids):
        lines.append(f"  - removed: {migration_id}")
    for migration_id in sorted(actual_ids - expected_ids):
        lines.append(f"  + added:   {migration_id}")
    for migration_id in sorted(actual_ids & expected_ids):
        if actual[migration_id] != expected[migration_id]:
            lines.append(
                f"  * changed: {migration_id}\n"
                f"      expected sha256={expected[migration_id]}\n"
                f"      actual   sha256={actual[migration_id]}"
            )
    return "\n".join(lines)


def check_or_write(migrations_dir: Path, *, write: bool) -> int:
    if not migrations_dir.is_dir():
        sys.stderr.write(f"ERROR: missing migrations dir: {migrations_dir}\n")
        return 2

    actual = _actual_manifest(migrations_dir)
    manifest_file = migrations_dir / "MANIFEST.lock"

    if write:
        manifest_file.write_text(_render_manifest(actual))
        sys.stdout.write(f"wrote {manifest_file} ({len(actual)} migration(s))\n")
        return 0

    if not manifest_file.exists():
        sys.stderr.write(
            f"FAIL: missing manifest: {manifest_file}\n"
            "      run: python tools/check_migration_manifest.py --write\n"
        )
        return 1

    expected = _parse_manifest(manifest_file.read_text(), manifest_path=manifest_file)
    label = _display_path(manifest_file)
    if expected == actual:
        sys.stdout.write(f"OK: {label} matches {len(actual)} migration(s)\n")
        return 0

    diff = _format_diff(actual, expected)
    sys.stderr.write(
        f"FAIL: {label} drifts from migrations dir:\n"
        f"{diff}\n"
        "      run: python tools/check_migration_manifest.py --write\n"
    )
    return 1


def _display_path(path: Path) -> str:
    """Show repo-relative path when possible, else absolute (for tmp_path tests)."""

    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="check_migration_manifest")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Regenerate MANIFEST.lock files instead of checking them.",
    )
    parser.add_argument(
        "--service",
        action="append",
        choices=("backend", "ai-backend"),
        help="Limit to one or more services (default: all).",
    )
    args = parser.parse_args(argv)

    selected: tuple[Path, ...] = SERVICE_MIGRATION_DIRS
    if args.service:
        wanted = set(args.service)
        selected = tuple(
            path for path in SERVICE_MIGRATION_DIRS if path.parents[0].name in wanted
        )

    failures = 0
    for migrations_dir in selected:
        rc = check_or_write(migrations_dir, write=args.write)
        if rc != 0:
            failures += 1

    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
