// Thin re-export wrapper. The Zod schemas live in chat-transport because
// the renderer also imports them (for the channel-name constants); main
// validates against the same source so both sides cannot drift.
export {
  CHANNELS,
  CHANNEL_VALUES,
  EmptyParamsSchema,
  IpcValidationError,
  isAllowedChannel,
  StreamEventKindSchema,
  StreamEventPayloadSchema,
  TransportRequestParamsSchema,
  TransportSubscribeParamsSchema,
  TransportUnsubscribeParamsSchema,
  AuthWorkspaceParamsSchema,
  RendererSessionSchema,
  Tier2InstallPayloadSchema,
  Tier2UninstallPayloadSchema,
  Tier2MarkBrokenPayloadSchema,
  Tier2BoundaryErrorPayloadSchema,
  BootPhaseSchema,
  BootStatusPayloadSchema,
  type AuthWorkspaceParams,
  type BootPhase,
  type BootStatusPayload,
  type ChannelName,
  type RendererSession,
  type StreamEventKind,
  type StreamEventPayload,
  type Tier2BoundaryErrorPayload,
  type Tier2InstallPayload,
  type Tier2MarkBrokenPayload,
  type Tier2UninstallPayload,
  type TransportRequestParams,
  type TransportSubscribeParams,
  type TransportUnsubscribeParams,
} from "@enterprise-search/chat-transport";
